# Generated by Django 6.0.1 on 2026-02-05 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(2)])),
                ('storyId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stories.story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
