# Generated by Django 6.0.1 on 2026-02-05 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markers', '0001_initial'),
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('content', models.TextField(max_length=2048, validators=[django.core.validators.MinLengthValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('markers', models.ManyToManyField(to='markers.marker')),
                ('writerId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='writers.writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
