# Generated by Django 6.0.1 on 2026-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='markers',
            field=models.ManyToManyField(blank=True, to='markers.marker'),
        ),
        migrations.AlterField(
            model_name='story',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
