# Generated by Django 6.0.1 on 2026-02-05 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('firstname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastname', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
