from typing import Generic, TypeVar, List

T = TypeVar("T")


class Repository(Generic[T]):
    def create(self, entity: T) -> T: ...
    def find_by_id(self, id: int) -> T: ...
    def find_all(self) -> List[T]: ...
    def update(self, id: int, entity: T) -> T: ...
    def delete(self, id: int) -> None: ...
